### ISSUE TITLE
Front page 'Chitinozoans' and 'Foraminiferans' missing on different lang options

### ISSUE THREAD

**Issue by enmust** [geocollections/fossiilid.info#124]
lang = SWE then both are missing
lang = FIN only Foraminiferans is missing

est and eng are ok

**Comment by ursulatoom** [comment]
???

https://edit2.geocollections.info/taxon/32
https://edit2.geocollections.info/taxon/34


Saadetud Windows 10 rakendusest Meil<https://go.microsoft.com/fwlink/?LinkId=550986>

Saatja: enmust<mailto:notifications@github.com>
Saadetud: kolmapäev, 9. september 2020 11:49
Adressaat: geocollections/fossiilid.info<mailto:fossiilid.info@noreply.github.com>
Koopia: Subscribed<mailto:subscribed@noreply.github.com>
Teema: [geocollections/fossiilid.info] Front page 'Chitinozoans' and 'Foraminiferans' missing on different lang options (#124)


lang = SWE then both are missing
lang = FIN only Foraminiferans is missing

est and eng are ok
