### ISSUE TITLE
Simple search improvement

### ISSUE THREAD

**Issue by OlesjaSenkiv** [geocollections/fossiilid.info#28]
Sometimes it is necessary to search taxon in Russian using Cyrillic letters. Simple search should include one more request to taxon_common_name table. https://api.geocollections.info/taxon_common_name/?paginate_by=30&multi_search=value:%D0%BC%D0%BE%D0%BB;fields:name;lookuptype:icontains

**Comment by ollehints** [comment]
see https://api.geocollections.info/taxon/?paginate_by=10&fields=id,taxon,common_name__name,taxon&multi_search=value:mol;fields:taxon,common_name__name;lookuptype:icontains
