### ISSUE TITLE
Classification tree taxon name truncated

### ISSUE THREAD

**Issue by ollehints** [geocollections/fossiilid.info#58]
On few occasions the taxon name gets truncated(?), for instance showing only "e" in case of https://fossiilid.geokogud.info/5370. The latter taxon has correct name however (https://fossiilid.geokogud.info/5379).

![image](https://user-images.githubusercontent.com/14974887/47352252-30787400-d6c2-11e8-8aff-e69164a26b9c.png)

**Comment by OlesjaSenkiv** [comment]
the following logic was implemented `_.includes(taxon.taxon, taxon.parent__taxon) ? taxon.taxon.replace(taxon.parent__taxon, "") : taxon.taxon;` In other words, there was the condition which checks whether taxon name contains parent taxon name as here http://fossiilid.info/2104
I added one more condition If name contains with more than 2 words. Is it correct?
