### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by OlesjaSenkiv** [geocollections/fossiilid.info#6]
Front page content (fossils groups) is loaded via API requesthttps://api.geocollections.info/taxon_page/?language=et&fields=frontpage
Acceptance criteria:
- Front page has following groups. Clicking on the group activate navigation to Item Page.
![image](https://user-images.githubusercontent.com/25752623/43049583-b9dfe0d8-8e02-11e8-89b0-4540d8cc390e.png)

**Comment by OlesjaSenkiv** [comment]
Currently api returns only 6 groups. Need to analyse if it is bug

**Comment by ollehints** [comment]
This was/is little problem with data. Now added two fields:
The API call should be: https://api.geocollections.info/taxon_page/?language=et&on_frontpage=1&order_by=frontpage_order&fields=frontpage,taxon

**Comment by OlesjaSenkiv** [comment]
The following API call https://api.geocollections.info/taxon_page/?language=et&on_frontpage=1&order_by=frontpage_order&fields=frontpage,taxon do not return result if language = en.

In case of estonian language, there is also a problem that only 10 results are returned
