### ISSUE TITLE
Item page>>References implementaion

### ISSUE THREAD

**Issue by OlesjaSenkiv** [geocollections/fossiilid.info#7]
Item page should load selection of related publications
![image](https://user-images.githubusercontent.com/25752623/43137846-ae3b6dca-8f55-11e8-9dd9-e5b98141e329.png)

all related data is loaded using following url:
https://api.geocollections.info/taxon_occurrence/?taxon=2104

**Comment by OlesjaSenkiv** [comment]
currently API do not return title and doi. Title can be reached from description table https://api.geocollections.info/taxon_description/?taxon=62

**Comment by ollehints** [comment]
reference_occurrence now returns title and DOI (and journal_name, book, number and pages).

**Comment by OlesjaSenkiv** [comment]
Where exactly journal_name, book, number and pages information should be loaded?

**Comment by ollehints** [comment]
ideally, if there is enough space, each listed reference should be composed of: author, year. title. journal_name: number or book, pages. DOI:doi.
