### ISSUE TITLE
problem with <i> tag style

### ISSUE THREAD

**Issue by ollehints** [geocollections/fossiilid.info#73]
For some reason `<i>` style tag changes also font size: https://fossiilid.geokogud.info/2120.
This should not be the case. Necessary properties should be changed using special style class or div id.

**Comment by OlesjaSenkiv** [comment]
Could you provide some screenshot. because in some blocks it was specially set to smaller font 
![image](https://user-images.githubusercontent.com/25752623/48478811-0ec86380-e80e-11e8-8442-e151186c4b61.png)

**Comment by ollehints** [comment]
actually it is the em tag. A screenshot:
![image](https://user-images.githubusercontent.com/14974887/48765865-cbfa0600-ecbb-11e8-906c-2c9f9c2db331.png)
