### ISSUE TITLE
Fossils simple search indexing

### ISSUE THREAD

**Issue by OlesjaSenkiv** [geocollections/fossiilid.info#74]
Use solr to improve searching speed.

**Comment by ollehints** [comment]
solr search now hides some values: search for 'kitiin' used to return a correct entry:
https://api.geocollections.info/taxon/?sql=simple_taxon_search&keyword=kitiin
not any more, as solr index does not hold multiple common names:
https://api.geocollections.info/solr/fossils_search/?q=name:*kitii*
speed is only slighly better with solr.
if to use solr, the index should be further tweaked and expanded, defining multi-value field for common_name.

**Comment by ollehints** [comment]
done
