### ISSUE TITLE
scrolling images

### ISSUE THREAD

**Issue by ollehints** [geocollections/fossiilid.info#76]
In some cases the same images are shown repeatedly: https://fossiilid.geokogud.info/10310
In most cases works as expected: https://fossiilid.geokogud.info/62
Can this be related to the number of records initially shown (before scrolling)?

**Comment by OlesjaSenkiv** [comment]
Actually it is api fault. If you set the number of pages to the number which is higher than actual total number of pages then you will always get as a result last page.
