### ISSUE TITLE
Item Page >> additional component

### ISSUE THREAD

**Issue by OlesjaSenkiv** [geocollections/fossiilid.info#9]
Synonymy list:
https://api.geocollections.info/taxon_synonym/?taxon=2114

Type specimen data:
https://api.geocollections.info/taxon_type_specimen/?taxon=2104

Collection specimens linked to species: 
https://api.geocollections.info/specimen/?specimenidentification__taxon_id=2104&fields=id&format=json

![image](https://user-images.githubusercontent.com/25752623/43180765-85c2a916-8fe2-11e8-9d4e-c9b9f62accd8.png)

**Comment by OlesjaSenkiv** [comment]
In case of type specimen data depth value can be returned with the following request
https://api.geocollections.info/taxon_type_specimen/?taxon=2104

Currently it can be accessed from https://api.geocollections.info/taxon_occurrence/?taxon=2104

Or second request could contain some field with value "holotüüp".
One more value does not returned:
![image](https://user-images.githubusercontent.com/25752623/43187110-479bca34-8ff9-11e8-9548-5a759b1e7636.png)

**Comment by OlesjaSenkiv** [comment]
Value "Kaljoprion laevaensis" can be reached from different sources (https://api.geocollections.info/taxon.json?id__in=1,29,38,60,61,62,259,1081,2104&fields=taxon,rank__rank_en) But other stuff where from I should use
![image](https://user-images.githubusercontent.com/25752623/43189241-c7ae48d2-8ffe-11e8-9006-fea8faba9d3a.png)

**Comment by ollehints** [comment]
The api call above is for retrieving list of all parents based on hierarchy_string.
The name of the current taxon should come from the taxon field of  https://api.geocollections.info/taxon/$id

The number of related specimens should be asked using:
https://api.geocollections.info/specimen/?specimenidentification__taxon_id=2104&fields=id&format=json&paginate_by=1
And then the "count" is the number to show.

**Comment by OlesjaSenkiv** [comment]
Distribution and references

![image](https://user-images.githubusercontent.com/25752623/43190274-50b497f6-9001-11e8-8d63-636a3952a643.png)

It is not clear for me what should I use

**Comment by OlesjaSenkiv** [comment]
Occurrence in micropaleontological samples:

Currently non of 14 prepared API requests do not return following information
![image](https://user-images.githubusercontent.com/25752623/43190749-660ed570-9002-11e8-8bf8-469e49c6c9f9.png)

**Comment by ollehints** [comment]
These come from the taxon_occurrence table. The records in this table may or may not include reference. Probably should be rethought from data perspective so that each record has a related reference.

**Comment by ollehints** [comment]
Heading should be "Occurrence in samples" / "Esinemine proovides".
Works for example: https://api.geocollections.info/taxon_list/?taxon=12851
The problem is that many taxa are related to samples using name (text field) rather than taxon_id. This should be corrected on data side.
